version: '3'

services:

  db:
    image: postgres:15
    container_name: postgres_container
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  adminer:
    image: adminer
    container_name: adminer_container
    restart: always
    ports:
      - '8080:8080'